include:
  remote: https://git.shivering-isles.com/container-library/build-ah-engine/-/raw/feature/multiarch/gitlab-ci-template.yml

variables:
  GIT_SUBMODULE_STRATEGY: 'recursive'
  CI_CONTAINER_BUILD_ARCHS: "amd64:arm64"
  CI_REGISTRY_IMAGE_VERSION: "0.5.2 --suffix=-1"
