image: quay.io/sheogorath/build-ah-engine

variables:
  GIT_SUBMODULE_STRATEGY: 'recursive'

before_script:
  - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-aarch64:
  stage: build
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" || true
    - podman build --layers=false --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" --format docker .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
  tags:
    - aarch64

build-amd64:
  stage: build
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" || true
    - podman build --layers=false --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" --format docker .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
  tags:
    - x86_64

deploy:
  stage: deploy
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
    - podman manifest create $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - podman manifest add --variant v8 $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman manifest add $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" 
    - podman manifest push --all --format v2s2 "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - x86_64

deploy-master:
  stage: deploy
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
    - podman manifest create "$CI_REGISTRY_IMAGE"
    - podman manifest add --variant v8 "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman manifest add "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" 
    - podman manifest push --all --format v2s2 "$CI_REGISTRY_IMAGE" "docker://$CI_REGISTRY_IMAGE:master"
    - podman manifest push --all --format v2s2 "$CI_REGISTRY_IMAGE" "docker://$CI_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - x86_64
