include:
  - project: 'container-library/build-ah-engine'
    ref: feature/multiarch
    file: '/gitlab-ci-template.yml'

variables:
  GIT_SUBMODULE_STRATEGY: 'recursive'
  CI_CONTAINER_BUILD_ARCHS: "amd64:arm64"
  CI_REGISTRY_IMAGE_VERSION: "0.5.2"
