image: registry.gitlab.com/othermo/fedora-build:latest

before_script:
  - git config --global user.email "info@othermo.de"
  - git config --global user.name "Othermo CI"
  - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  script:
    - podman pull $CI_REGISTRY_IMAGE:latest || true
    - podman build --layers=false --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:latest .
    - podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - podman push $CI_REGISTRY_IMAGE:latest
  only:
    # this build script would conflict with other branches
    - master
  tags:
    - aarch64

build:
  script:
    - podman pull $CI_REGISTRY_IMAGE:latest || true
    - podman build --layers=false --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    # this build script would conflict with other branches
    - master
  tags:
    - aarch64
