image: quay.io/sheogorath/build-ah-engine

variables:
  GIT_SUBMODULE_STRATEGY: 'recursive'

before_script:
  - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-aarch64:
  image: docker.io/library/fedora:32
  stage: build
  before_script:
    # Build engine for aarch64
    - dnf install -y git podman buildah findutils
    - sed -e 's/cgroup_manager =.*/cgroup_manager = "cgroupfs"/' /usr/share/containers/containers.conf > /etc/containers/containers.conf
    - git config --global user.email "info@othermo.de"
    - git config --global user.name "Othermo CI"
    - cp storage.conf /etc/containers/storage.conf
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" || true
    - podman build --layers=false --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
  tags:
    - aarch64

build-amd64:
  stage: build
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" || true
    - podman build --layers=false --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" .
    - podman push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
  tags:
    - x86_64

deploy:
  stage: deploy
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
    - podman manifest create $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" 
    - podman manifest push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - x86_64

deploy-master:
  stage: deploy
  script:
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64"
    - podman pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64"
    - podman manifest create $CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-aarch64" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-amd64" 
    - podman manifest push "$CI_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - x86_64
